name: Update Stats

on:
  schedule:
    - cron: "0 3 * * 3,6"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install dependencies
        run: |
          gem install nokogiri open-uri json

      - name: Run scraper to update stats
        run: ruby .github/workflows/update_stats.rb

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stats.json
          git commit -m "Update stats [skip ci]" || echo "No changes to commit"
          git push
